// Vercel构建脚本
const { execSync } = require('child_process');
const fs = require('fs');

// 检查迁移锁定文件
try {
  console.log('检查迁移配置...');
  const migrationLockPath = './prisma/migrations/migration_lock.toml';
  
  // 确保迁移锁文件内容正确
  const content = '# Please do not edit this file manually\n# It should be added in your version-control system (i.e. Git)\nprovider = "postgresql"';
  console.log('更新迁移锁定文件...');
  fs.writeFileSync(migrationLockPath, content, 'utf8');
} catch (error) {
  console.warn('更新迁移锁定文件失败，但将继续执行:', error.message);
}

// 首先运行Prisma初始化
try {
  console.log('执行Prisma数据库初始化...');
  
  // 生成Prisma客户端
  console.log('生成Prisma客户端...');
  execSync('npx prisma generate', { stdio: 'inherit' });
  
  // 尝试执行迁移
  try {
    console.log('应用数据库迁移...');
    execSync('npx prisma migrate deploy', { stdio: 'inherit' });
  } catch (migrateError) {
    console.error('迁移失败，但将继续构建过程:', migrateError.message);
  }
  
  // 然后执行正常的构建过程
  console.log('执行项目构建...');
  execSync('yarn mask && next build', { stdio: 'inherit' });
  
  console.log('构建完成！');
} catch (error) {
  console.error('构建失败:', error);
  process.exit(1);
} 