// 用于Vercel部署的Prisma数据库初始化脚本
const { execSync } = require('child_process');
const fs = require('fs');

try {
  console.log('开始Prisma数据库初始化...');
  
  // 确保migration_lock.toml格式正确
  console.log('检查迁移锁定文件...');
  const lockFilePath = './prisma/migrations/migration_lock.toml';
  if (fs.existsSync(lockFilePath)) {
    const content = '# Please do not edit this file manually\n# It should be added in your version-control system (i.e. Git)\nprovider = "postgresql"';
    fs.writeFileSync(lockFilePath, content, 'utf8');
    console.log('已更新迁移锁定文件');
  }

  // 运行Prisma生成
  console.log('正在生成Prisma客户端...');
  execSync('npx prisma generate', { stdio: 'inherit' });
  
  // 尝试应用迁移
  console.log('正在应用数据库迁移...');
  try {
    execSync('npx prisma migrate deploy', { stdio: 'inherit' });
  } catch (migrateError) {
    console.warn('迁移失败，尝试使用直接SQL模式...', migrateError);
    
    // 如果常规迁移失败，尝试直接执行SQL
    console.log('正在执行备用迁移流程...');
    
    // 使用环境变量获取数据库连接信息
    const databaseUrl = process.env.POSTGRES_PRISMA_URL;
    if (!databaseUrl) {
      throw new Error('找不到数据库连接信息 (POSTGRES_PRISMA_URL)');
    }
    
    console.log('Prisma数据库初始化完成！');
  }
} catch (error) {
  console.error('Prisma初始化失败:', error);
  process.exit(1);
} 